### ISSUE TITLE
Failed to download step after recent 1.3.1 release

### ISSUE THREAD

**Issue by mrister** [Almouro/bitrise-nvm-step#16]
Has the release been done fully ?
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/1213258/179955416-1caced16-f962-427a-b6a5-029458f119e5.png">

**Comment by adamivancza** [comment]
yeah I can see the same issue on our builds

**Comment by ZioCain** [comment]
Same here.
Applied the workaround to manually set the version 1.3.0 (through bitrise.yml) and it worked.

On a side note, version 1.2.2 will also break

**Comment by Almouro** [comment]
Damn, seems like there are some issues on nvm https://github.com/nvm-sh/nvm/issues/1985 about exiting with code 3 

I couldn't quickly find a fix so I'll revert so that the folks on auto update don't have their CI suddenly crashing for no reason

**Comment by Almouro** [comment]
Here's the PR on the Bitrise step lib https://github.com/bitrise-io/bitrise-steplib/pull/3553

Sorry everyone, didn't imagine that a simple `set -e` would break this much. 
If I do re-release the `set -e`, I'll make it a breaking change in the versioning to be safe

**Comment by mrister** [comment]
Thanks @Almouro

**Comment by ronenempathy** [comment]
any update on this ?

**Comment by Almouro** [comment]
Hi @ronenempathy, version `1.3.2` of the nvm step should revert the breaking change and work
Let me know if it doesn't!
